env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
    - /bin/bash -c "echo -e $COSIGN_KEY > cosign.key"
    - /bin/bash -c "echo -e $COSIGN_PUB > cosign.pub"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

builds:
  - env:
      - CGO_ENABLED=0 
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - 'ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=transfer-service"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

  - image_templates:
      - 'ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-arm64'
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.description=transfer-service"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"

docker_manifests:
  - name_template: 'ghcr.io/jaskaransm/transfer-service:{{ .Tag }}'
    image_templates:
      - "ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-amd64"
      - "ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-arm64"

  - name_template: 'ghcr.io/jaskaransm/transfer-service:latest'
    image_templates:
      - "ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-amd64"
      - "ghcr.io/jaskaransm/transfer-service:{{ .Tag }}-arm64"

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
    - goos: windows
      format: zip
    # files:
    #   - README.md
    #   - sample_config.json

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PWD }}'
    artifacts: checksum
    args:
      - sign-blob
      - '--key=cosign.key'
      - '--output-signature=${signature}'
      - '${artifact}'

docker_signs:
- cmd: cosign
  stdin: '{{ .Env.COSIGN_PWD }}'
  artifacts: manifests
  args:
  - 'sign'
  - '--key=cosign.key'
  - '${artifact}'

release:
  footer: |
    **Full Changelog**: https://github.com/jaskaranSM/transfer-service/compare/{{ .PreviousTag }}...{{ .Tag }}
  
  extra_files:
    - glob: "cosign.pub"


# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
